export const SET_PROFILE = "SET_PROFILE";
export const LOGOUT = "LOGOUT";
export const SET_ADV = "SET_ADV"
export const SET_NEWS = 'SET_NEWS'
export const HIDE_ALERT = 'HIDE_ALERT'
export const SHOW_ALERT = 'SHOW_ALERT'
export const SET_NEWS_IMG = "SET_NEWS_IMG"
export const SET_SINGLE_NEWS = "SET_SINGLE_NEWS"
export const SET_PARTNERS = "SET_PARTNERS"
export const SET_PARTNERS_IMG = "SET_PARTNERS_IMG"
export const DELETE_NEWS = "DELETE_NEWS";
export const DELETE_ADV = 'DELETE_ADV'
export const DELETE_PARTNERS = 'DELETE_PARTNERS'
export const SET_SHEDULE = "SET_SHEDULE"
export const SET_SHEDULE_FILE = "SET_SHEDULE_FILE"
export const SET_SINGLE_PARTNER = "SET_SINGLE_PARTNER"
// export const ADD_NEWS = 'ADD_NEWS'
export const SET_PAGE = "SET_PAGE"